	git add   registry/ui-macros.json
	git add   screen/moquiai/js/MoquiAiApp.qvt.js
	git add   screen/moquiai/js/MoquiCanvasEditor.qvt.js
	git add   service/moquiai.rest.xml
	git add   service/moquiai/AppServices.xml
	git add   service/moquiai/BlueprintServices_getBlueprint.groovy
	git add   service/moquiai/BlueprintServices_renderBlueprintShell.groovy
	git add   status.sh
	git add   webroot/js/BlueprintClient.js
	git add registry/service-macros.json
	git add rest/
	git add schema/aitree-screen.schema.json
