import org.moqui.context.ExecutionContext
import groovy.json.JsonBuilder

ExecutionContext ec = context.ec
String componentName = context.componentName

if (!componentName || componentName.contains(" ") || componentName.contains(".")) {
    return [success: false, message: "Invalid component name. No spaces or dots."]
}

File runtimeDir = new File(ec.factory.runtimePath)
File compRoot = new File(runtimeDir, "component/${componentName}")

if (compRoot.exists()) {
    return [success: false, message: "Component '${componentName}' already exists."]
}

try {
    // 1. Create directory structure
    compRoot.mkdirs()
    new File(compRoot, "screen").mkdirs()
    new File(compRoot, "service").mkdirs()
    new File(compRoot, "rest").mkdirs()
    
    // 2. Create Welcome.json blueprint
    def welcomeJson = [
        meta: [
            title: "${componentName} Dashboard",
            intent: "Landing page for new project ${componentName}",
            hipaa_audit: true
        ],
        context: [
            entity: "mantle.party.Person",
            id: "10001"
        ],
        structure: [
            ([
                id: "welcomeHeader",
                component: "header",
                properties: [ text: "Welcome to ${componentName} Architectural Workspace" ]
            ] as Map),
            ([
                id: "instructionText",
                component: "displayfield",
                properties: [ label: "Next Step", value: "Command the AI to model your first entity (e.g., 'Add a Product block')." ]
            ] as Map)
        ]
    ] as Map
    
    File welcomeFile = new File(compRoot, "screen/Welcome.json")
    welcomeFile.text = new JsonBuilder(welcomeJson).toPrettyString()

    // 2.5 Create Welcome.xml shadow
    File welcomeXml = new File(compRoot, "screen/Welcome.xml")
    welcomeXml.text = """<?xml version="1.0" encoding="UTF-8"?>
<screen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://moqui.org/xsd/xml-screen-3.xsd">
    <widgets>
        <label text="Rendering via Aitree Blueprint..."/>
    </widgets>
</screen>"""

    // 3. Create component-level rest.xml stub
    File restFile = new File(compRoot, "rest/s1/rest.xml")
    restFile.parentFile.mkdirs()
    restFile.text = """<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://moqui.org/xsd/rest-api-1.1.xsd"
          name="${componentName}" require-authentication="false">
    <!-- Generated by Aitree AI Peer Assistant -->
</resource>
"""

    return [success: true, message: "Project '${componentName}' created successfully with initial Welcome screen."]
} catch (Exception e) {
    ec.logger.error("Failed to create component: ${e.message}", e)
    return [success: false, message: "Failed: " + e.message]
}
